# Generated by Django 5.1.4 on 2025-03-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourismMS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
