# Generated by Django 5.1.4 on 2025-03-22 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourismMS', '0002_attraction_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('approved', 'Approved'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
    ]
